### ISSUE TITLE
Partially working under Gnome 3.26

### ISSUE THREAD

**Issue by sojusnik** [rockon999/dynamic-panel-transparency#78]
After updating to v23 your extension stopped working properly. So the panel remains always at 0% transparency. Only when switching to the Gnome overview, the panel gets transparent again.

What's the proper way to debug this?

Observed under Ubuntu Gnome 17.04 with mostly Gnome 3.24.

**Comment by rockon999** [comment]
If you could disable/enable the extension and then send me any relevant logs from from `journalctl --since "30 seconds ago"` altering the number of seconds as needed. Sorry about this, I'm on 3.24 and it's running fine so that is a bit odd! You can always downgrade to v20 when done debugging.

**Comment by rockon999** [comment]
@sojusnik You should also try enabling 'disable excess styling' in the settings, that can sometimes fix issues.

**Comment by rockon999** [comment]
Also, could you give me your exact Shell version? `gnome-shell --version`

**Comment by sojusnik** [comment]
`disable excess styling` didn't help.

It seems, that my current shell theme is the cause! With the default (Adwaita) one, it works well. Actually my current theme is the default one, but with a different font. For that, I've created gnome-shell.css under ~/.local/share/themes/mytheme/gnome-shell/ with the following content:

> stage {
>   font-family: Ubuntu;
>   font-size: 10pt; }

My Gnome Shell version is 3.24.2.

Do you still need logs from `journalctl`?

**Comment by sojusnik** [comment]
That's weird! I've removed spaces, so it's now written in one word, in the theme's folder name and my current theme started to work fine!

**Comment by rockon999** [comment]
It's possible that an error in your theme customization was preventing this extension from working properly. The newest versions of this extension use Gnome's CSS engine instead of painting the effect directly on the panel, so that is why this issue sprung up.

**Comment by sojusnik** [comment]
Although the transition effect itself is working fine now, windows aren't still detected properly, as described [here](https://github.com/rockon999/dynamic-panel-transparency/issues/63) and shown in this new [screencast](https://mega.nz/#!yh5mTa4L!KyFdlUe6QuzC_MgluMKVOJ_KgqmziEymZL1RgSx3VK4).

**Comment by rockon999** [comment]
@sojusnik Okay, I understand the problem now. I fixed #63 but only for top panels, I'll push another fix for bottom panels.

**Comment by rockon999** [comment]
As of [dc229aa](https://github.com/rockon999/dynamic-panel-transparency/commit/dc229aa511c0d81c3033ab3b91ae0ee98b8d71aa) (current master) this issue should be fixed.

**Comment by sojusnik** [comment]
Still doesn't work with the latest version of your extension on Ubuntu 17.10 with Gnome 3.26 and the new Ubuntu [Gnome-Shell theme](https://askubuntu.com/questions/969657/how-to-install-the-latest-ubuntu-17-10-shell-theme-under-ubuntu-with-vanilla-gno) in connection with the latest [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/), as shown [here](https://mega.nz/#!L4AjSIBT!cfqRQ-gqB3_lMF8nqYvY-JquZ1HceFVdSivN5e_zpQQ).

**Comment by rockon999** [comment]
@sojusnik Have you tried the latest from the GitHub?

**Comment by sojusnik** [comment]
Now it seems to work, thanks!
